import oldGlyphs from './old-glyphs'
import {
  mdiAccount,
  mdiAccountGroup,
  mdiAccountStar,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiArrowLeft,
  mdiBackburger,
  mdiBookOpenOutline,
  mdiBriefcaseVariant,
  mdiBullhorn,
  mdiCalendar,
  mdiCart,
  mdiCash,
  mdiChartBar,
  mdiCheck,
  mdiCheckBold,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiCheckCircle,
  mdiChevronLeft,
  mdiChevronRight,
  mdiClipboardCheckOutline,
  mdiClose,
  mdiCog,
  mdiCogOutline,
  mdiCommentQuote,
  mdiCompass,
  mdiCreditCardCheckOutline,
  mdiCreditCardRemoveOutline,
  mdiCreditCardSettingsOutline,
  mdiCurrencyEur,
  mdiDeleteForever,
  mdiDotsHorizontal,
  mdiEye,
  mdiEyeOff,
  mdiFaceAgent,
  mdiFileAlert,
  mdiFileDocumentOutline,
  mdiFormatColorFill,
  mdiFormatQuoteClose,
  mdiFormatQuoteOpen,
  mdiForwardburger,
  mdiFullscreen,
  mdiHandshake,
  mdiHeart,
  mdiImage,
  mdiInformation,
  mdiKeyboardBackspace,
  mdiKeyLink,
  mdiKeyRemove,
  mdiLink,
  mdiLoading,
  mdiLock,
  mdiLockOutline,
  mdiLogoutVariant,
  mdiMenuDown,
  mdiMenuUp,
  mdiPencil,
  mdiPlus,
  mdiMinus,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiReceipt,
  mdiRestore,
  mdiSchool,
  mdiShieldCheckOutline,
  mdiShopping,
  mdiShoppingOutline,
  mdiSquareMediumOutline,
  mdiStar,
  mdiStarOutline,
  mdiSwapHorizontal,
  mdiWeb,
  mdiXml,
  mdiBadgeAccountHorizontal,
  mdiCubeOutline,
  mdiFolderOutline,
  mdiFileCodeOutline,
  mdiContentCopy,
  mdiUndo,
  mdiEarth,
  mdiCellphoneLink,
  mdiChevronDownCircleOutline,
  mdiChevronUpCircleOutline,
  mdiRocket,
  mdiClipboardText,
  mdiFolder,
  mdiMap,
  mdiCheckboxBlank,
  mdiInformationOutline,
  mdiCloseCircleOutline,
  mdiCircleOutline,
  mdiShareVariant,
  mdiMenu,
  mdiMapMarkerOutline,
  mdiArrowLeftThinCircleOutline,
  mdiThumbUp,
  mdiBook,
  mdiViewGrid,
  mdiFileOutline,
  mdiAccountOutline,
  mdiBackspaceOutline,
  mdiViewGridPlus,
  mdiFormatText,
  mdiArchiveOutline,
  mdiClockOutline,
  mdiKey,
  mdiSpeedometer,
  mdiClipboard,
  mdiTagOutline,
  mdiEmailOutline,
  mdiFormatListBulleted,
  mdiGift,
  mdiFilePlusOutline,
  mdiCellphone,
  mdiTable,
  mdiBellAlertOutline,
  mdiBellOutline,
  mdiCreditCard,
  mdiCreditCardOutline,
  mdiShield,
  mdiShieldOffOutline,
  mdiDelete,
  mdiLaptop,
  mdiMapMarkerPath,
  mdiCashRegister,
  mdiViewDayOutline,
  mdiTab,
  mdiTabRemove
} from '@mdi/js'

const baseIcons = {
  eye: mdiEye,
  eyeNo: mdiEyeOff,
  menuUp: mdiMenuUp,
  menuDown: mdiMenuDown,
  starOutline: mdiStarOutline,
  star: mdiStar,
  plus: mdiPlus,
  minus: mdiMinus,
  lockOutline: mdiLockOutline,
  checkBold: mdiCheckBold,
  fileAlert: mdiFileAlert,
  alertCircle: mdiAlertCircle,
  fullscreen: mdiFullscreen,
  keyboardBackspace: mdiKeyboardBackspace,
  discover: mdiCompass,
  shoppingOutline: mdiShoppingOutline,
  cog: mdiCog,
  cogOutline: mdiCogOutline,
  logout: mdiLogoutVariant,
  shopping: mdiShopping,
  close: mdiClose,
  customers: mdiAccountStar,
  lock: mdiLock,
  xml: mdiXml,
  colorFill: mdiFormatColorFill,
  cart: mdiCart,
  chartBar: mdiChartBar,
  business: mdiBriefcaseVariant,
  handshake: mdiHandshake,
  users: mdiAccountGroup,
  school: mdiSchool,
  faceAgent: mdiFaceAgent,
  calendar: mdiCalendar,
  receipt: mdiReceipt,
  settingsOutline: mdiCreditCardSettingsOutline,
  checkboxBlankOutline: mdiCheckboxBlankOutline,
  checkboxMarked: mdiCheckboxMarked,
  back: mdiArrowLeft,
  information: mdiInformation,
  check: mdiCheck,
  checkCircle: mdiCheckCircle,
  swapHorizontal: mdiSwapHorizontal,
  heart: mdiHeart,
  chevronLeft: mdiChevronLeft,
  chevronRight: mdiChevronRight,
  link: mdiLink,
  clipboardCheckOutline: mdiClipboardCheckOutline,
  alertCircleOutline: mdiAlertCircleOutline,
  radioboxMarked: mdiRadioboxMarked,
  radioboxBlank: mdiRadioboxBlank,
  creditCardRemoveOutline: mdiCreditCardRemoveOutline,
  shieldCheckOutline: mdiShieldCheckOutline,
  creditCardCheckOutline: mdiCreditCardCheckOutline,
  restore: mdiRestore,
  edit: mdiPencil,
  keyLink: mdiKeyLink,
  squareMediumOutline: mdiSquareMediumOutline,
  web: mdiWeb,
  bullhorn: mdiBullhorn,
  formatQuoteOpen: mdiFormatQuoteOpen,
  formatQuoteClose: mdiFormatQuoteClose,
  currencyEur: mdiCurrencyEur,
  cash: mdiCash,
  bookOpenOutline: mdiBookOpenOutline,
  dotsH: mdiDotsHorizontal,
  image: mdiImage,
  keyRemove: mdiKeyRemove,
  account: mdiAccount,
  loading: mdiLoading,
  commentQuote: mdiCommentQuote,
  fileDocumentOutline: mdiFileDocumentOutline,
  deleteForever: mdiDeleteForever,
  forwardburger: mdiForwardburger,
  backburger: mdiBackburger,
  badgeAccountHorizontal: mdiBadgeAccountHorizontal,
  cubeOutline: mdiCubeOutline,
  folder: mdiFolder,
  folderOutline: mdiFolderOutline,
  fileCodeOutline: mdiFileCodeOutline,
  copy: mdiContentCopy,
  undo: mdiUndo,
  globe: mdiEarth,
  devices: mdiCellphoneLink,
  circleArrowTop: mdiChevronUpCircleOutline,
  circleArrowBottom: mdiChevronDownCircleOutline,
  rocket: mdiRocket,
  clipboardText: mdiClipboardText,
  map: mdiMap,
  color: mdiCheckboxBlank,
  checkboxBlank: mdiCheckboxBlank,
  info: mdiInformationOutline,
  checkmark: mdiCheck,
  circleX: mdiCloseCircleOutline,
  circle: mdiCircleOutline,
  share: mdiShareVariant,
  menu: mdiMenu,
  pin: mdiMapMarkerOutline,
  circleArrowLeft: mdiArrowLeftThinCircleOutline,
  thumbsUp: mdiThumbUp,
  book: mdiBook,
  grid: mdiViewGrid,
  file: mdiFileOutline,
  user: mdiAccountOutline,
  delete: mdiBackspaceOutline,
  apps: mdiViewGridPlus,
  text: mdiFormatText,
  box: mdiArchiveOutline,
  time: mdiClockOutline,
  fileCode: mdiFileCodeOutline,
  key: mdiKey,
  dashboard: mdiSpeedometer,
  clipboard: mdiClipboard,
  tag: mdiTagOutline,
  mail: mdiEmailOutline,
  list: mdiFormatListBulleted,
  gift: mdiGift,
  filePlus: mdiFilePlusOutline,
  mobile: mdiCellphone,
  table: mdiTable,
  bellAlert: mdiBellAlertOutline,
  bell: mdiBellOutline,
  creditcardFace: mdiCreditCard,
  creditcard: mdiCreditCardOutline,
  fileText: mdiFileDocumentOutline,
  shieldOk: mdiShieldCheckOutline,
  shield: mdiShield,
  shieldNo: mdiShieldOffOutline,
  trash: mdiDelete,
  iphone: mdiCellphone,
  laptop: mdiLaptop,
  route: mdiMapMarkerPath,
  cashRegister: mdiCashRegister,
  tab: mdiTab,
  tabRemove: mdiTabRemove,
  viewDayOutline: mdiViewDayOutline
}

const oldIconNames = {
  viewDayOutline: ['form'],
  tabRemove: ['browserNo'],
  tab: ['browser'],
  cashRegister: ['pos']
}

const populateIcons = () => {
  let backwardsCompatibilityIcons = {}

  Object.keys(oldIconNames).forEach(iconName =>
    oldIconNames[iconName].forEach(alias => {
      backwardsCompatibilityIcons[alias] = baseIcons[iconName]
    })
  )

  return {
    ...baseIcons,
    ...backwardsCompatibilityIcons
  }
}

export default populateIcons()
