import {
  mdiAccount,
  mdiAccountGroup,
  mdiAccountStar,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiArrowLeft,
  mdiBackburger,
  mdiBookOpenOutline,
  mdiBriefcaseVariant,
  mdiBullhorn,
  mdiCalendar,
  mdiCart,
  mdiCash,
  mdiChartBar,
  mdiCheck,
  mdiCheckBold,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiCheckCircle,
  mdiChevronLeft,
  mdiChevronRight,
  mdiClipboardCheckOutline,
  mdiClose,
  mdiCog,
  mdiCogOutline,
  mdiCommentQuote,
  mdiCompass,
  mdiCreditCardCheckOutline,
  mdiCreditCardRemoveOutline,
  mdiCreditCardSettingsOutline,
  mdiCurrencyEur,
  mdiDeleteForever,
  mdiDotsHorizontal,
  mdiEye,
  mdiEyeOff,
  mdiFaceAgent,
  mdiFileAlert,
  mdiFileDocumentOutline,
  mdiFormatColorFill,
  mdiFormatQuoteClose,
  mdiFormatQuoteOpen,
  mdiForwardburger,
  mdiFullscreen,
  mdiHandshake,
  mdiHeart,
  mdiImage,
  mdiInformation,
  mdiKeyboardBackspace,
  mdiKeyLink,
  mdiKeyRemove,
  mdiLink,
  mdiLoading,
  mdiLock,
  mdiLockOutline,
  mdiLogoutVariant,
  mdiMenuDown,
  mdiMenuUp,
  mdiPencil,
  mdiPlus,
  mdiMinus,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiReceipt,
  mdiRestore,
  mdiSchool,
  mdiShieldCheckOutline,
  mdiShopping,
  mdiShoppingOutline,
  mdiSquareMediumOutline,
  mdiStar,
  mdiStarOutline,
  mdiSwapHorizontal,
  mdiWeb,
  mdiXml,
  mdiBadgeAccountHorizontal,
  mdiCubeOutline,
  mdiFolderOutline,
  mdiFileCodeOutline,
  mdiContentCopy,
  mdiUndo,
  mdiEarth,
  mdiCellphoneLink,
  mdiChevronDownCircleOutline,
  mdiChevronUpCircleOutline,
  mdiRocket,
  mdiClipboardText,
  mdiFolder,
  mdiMap,
  mdiCheckboxBlank,
  mdiInformationOutline,
  mdiCloseCircleOutline,
  mdiCircleOutline,
  mdiShareVariant,
  mdiMenu,
  mdiMapMarkerOutline,
  mdiArrowLeftThinCircleOutline,
  mdiThumbUp,
  mdiBook,
  mdiViewGrid,
  mdiFileOutline,
  mdiAccountOutline,
  mdiBackspaceOutline,
  mdiViewGridPlus,
  mdiFormatText,
  mdiArchiveOutline,
  mdiClockOutline,
  mdiKey,
  mdiSpeedometer,
  mdiClipboard,
  mdiTagOutline,
  mdiEmailOutline,
  mdiFormatListBulleted,
  mdiGift,
  mdiFilePlusOutline,
  mdiCellphone,
  mdiTable,
  mdiBellAlertOutline,
  mdiBellOutline,
  mdiCreditCard,
  mdiCreditCardOutline,
  mdiShield,
  mdiShieldOffOutline,
  mdiDelete,
  mdiLaptop,
  mdiMapMarkerPath,
  mdiCashRegister,
  mdiViewDayOutline,
  mdiTab,
  mdiTabRemove,
  mdiMagnify
} from '@mdi/js'

export const baseIcons = {
  accountGroup: mdiAccountGroup,
  accountStar: mdiAccountStar,
  alertCircle: mdiAlertCircle,
  alertCircleOutline: mdiAlertCircleOutline,
  arrowLeft: mdiArrowLeft,
  backburger: mdiBackburger,
  bookOpenOutline: mdiBookOpenOutline,
  briefcaseVariant: mdiBriefcaseVariant,
  bullhorn: mdiBullhorn,
  calendar: mdiCalendar,
  cart: mdiCart,
  cash: mdiCash,
  chartBar: mdiChartBar,
  check: mdiCheck,
  checkBold: mdiCheckBold,
  checkboxBlankOutline: mdiCheckboxBlankOutline,
  checkboxMarked: mdiCheckboxMarked,
  checkCircle: mdiCheckCircle,
  chevronLeft: mdiChevronLeft,
  chevronRight: mdiChevronRight,
  clipboardCheckOutline: mdiClipboardCheckOutline,
  close: mdiClose,
  cog: mdiCog,
  cogOutline: mdiCogOutline,
  commentQuote: mdiCommentQuote,
  compass: mdiCompass,
  creditCardCheckOutline: mdiCreditCardCheckOutline,
  creditCardRemoveOutline: mdiCreditCardRemoveOutline,
  creditCardSettingsOutline: mdiCreditCardSettingsOutline,
  currencyEur: mdiCurrencyEur,
  deleteForever: mdiDeleteForever,
  dotsHorizontal: mdiDotsHorizontal,
  eye: mdiEye,
  eyeOff: mdiEyeOff,
  faceAgent: mdiFaceAgent,
  fileAlert: mdiFileAlert,
  fileDocumentOutline: mdiFileDocumentOutline,
  formatColorFill: mdiFormatColorFill,
  formatQuoteClose: mdiFormatQuoteClose,
  formatQuoteOpen: mdiFormatQuoteOpen,
  forwardburger: mdiForwardburger,
  fullscreen: mdiFullscreen,
  handshake: mdiHandshake,
  heart: mdiHeart,
  image: mdiImage,
  information: mdiInformation,
  keyboardBackspace: mdiKeyboardBackspace,
  keyLink: mdiKeyLink,
  keyRemove: mdiKeyRemove,
  link: mdiLink,
  loading: mdiLoading,
  lock: mdiLock,
  lockOutline: mdiLockOutline,
  logoutVariant: mdiLogoutVariant,
  menuDown: mdiMenuDown,
  menuUp: mdiMenuUp,
  pencil: mdiPencil,
  plus: mdiPlus,
  minus: mdiMinus,
  radioboxBlank: mdiRadioboxBlank,
  radioboxMarked: mdiRadioboxMarked,
  receipt: mdiReceipt,
  restore: mdiRestore,
  school: mdiSchool,
  shieldCheckOutline: mdiShieldCheckOutline,
  shopping: mdiShopping,
  shoppingOutline: mdiShoppingOutline,
  squareMediumOutline: mdiSquareMediumOutline,
  star: mdiStar,
  starOutline: mdiStarOutline,
  swapHorizontal: mdiSwapHorizontal,
  web: mdiWeb,
  xml: mdiXml,
  badgeAccountHorizontal: mdiBadgeAccountHorizontal,
  cubeOutline: mdiCubeOutline,
  folderOutline: mdiFolderOutline,
  fileCodeOutline: mdiFileCodeOutline,
  contentCopy: mdiContentCopy,
  undo: mdiUndo,
  earth: mdiEarth,
  cellphoneLink: mdiCellphoneLink,
  chevronDownCircleOutline: mdiChevronDownCircleOutline,
  chevronUpCircleOutline: mdiChevronUpCircleOutline,
  rocket: mdiRocket,
  clipboardText: mdiClipboardText,
  folder: mdiFolder,
  map: mdiMap,
  checkboxBlank: mdiCheckboxBlank,
  informationOutline: mdiInformationOutline,
  closeCircleOutline: mdiCloseCircleOutline,
  circleOutline: mdiCircleOutline,
  shareVariant: mdiShareVariant,
  menu: mdiMenu,
  mapMarkerOutline: mdiMapMarkerOutline,
  arrowLeftThinCircleOutline: mdiArrowLeftThinCircleOutline,
  thumbUp: mdiThumbUp,
  book: mdiBook,
  viewGrid: mdiViewGrid,
  fileOutline: mdiFileOutline,
  accountOutline: mdiAccountOutline,
  backspaceOutline: mdiBackspaceOutline,
  viewGridPlus: mdiViewGridPlus,
  formatText: mdiFormatText,
  archiveOutline: mdiArchiveOutline,
  clockOutline: mdiClockOutline,
  key: mdiKey,
  speedometer: mdiSpeedometer,
  clipboard: mdiClipboard,
  tagOutline: mdiTagOutline,
  emailOutline: mdiEmailOutline,
  formatListBulleted: mdiFormatListBulleted,
  gift: mdiGift,
  filePlusOutline: mdiFilePlusOutline,
  cellphone: mdiCellphone,
  table: mdiTable,
  bellAlertOutline: mdiBellAlertOutline,
  bellOutline: mdiBellOutline,
  creditCard: mdiCreditCard,
  creditCardOutline: mdiCreditCardOutline,
  shield: mdiShield,
  shieldOffOutline: mdiShieldOffOutline,
  delete: mdiDelete,
  laptop: mdiLaptop,
  mapMarkerPath: mdiMapMarkerPath,
  cashRegister: mdiCashRegister,
  viewDayOutline: mdiViewDayOutline,
  tab: mdiTab,
  tabRemove: mdiTabRemove,
  magnify: mdiMagnify
}

/**
 * Alternates
 *  - key is the alternate (old name)
 *  - value is our actual
 */
export const alternates = {
  // old icons = backwards compatibility
  form: mdiViewDayOutline,
  browserNo: mdiTabRemove,
  browser: mdiTab,
  pos: mdiCashRegister,
  eyeNo: mdiEyeOff,
  discover: mdiCompass,
  logout: mdiLogoutVariant,
  customers: mdiAccountStar,
  colorFill: mdiFormatColorFill,
  business: mdiBriefcaseVariant,
  users: mdiAccountGroup,
  settingsOutline: mdiCreditCardSettingsOutline,
  back: mdiArrowLeft,
  edit: mdiPencil,
  dotsH: mdiDotsHorizontal,
  account: mdiAccount,
  copy: mdiContentCopy,
  globe: mdiEarth,
  devices: mdiCellphoneLink,
  circleArrowTop: mdiChevronUpCircleOutline,
  circleArrowBottom: mdiChevronDownCircleOutline,
  color: mdiCheckboxBlank,
  info: mdiInformationOutline,
  checkmark: mdiCheck,
  circleX: mdiCloseCircleOutline,
  circle: mdiCircleOutline,
  share: mdiShareVariant,
  pin: mdiMapMarkerOutline,
  circleArrowLeft: mdiArrowLeftThinCircleOutline,
  thumbsUp: mdiThumbUp,
  grid: mdiViewGrid,
  file: mdiFileOutline,
  user: mdiAccountOutline,
  apps: mdiViewGridPlus,
  text: mdiFormatText,
  box: mdiArchiveOutline,
  time: mdiClockOutline,
  fileCode: mdiFileCodeOutline,
  dashboard: mdiSpeedometer,
  tag: mdiTagOutline,
  mail: mdiEmailOutline,
  list: mdiFormatListBulleted,
  filePlus: mdiFilePlusOutline,
  mobile: mdiCellphone,
  bellAlert: mdiBellAlertOutline,
  bell: mdiBellOutline,
  creditcardFace: mdiCreditCard,
  creditcard: mdiCreditCardOutline,
  fileText: mdiFileDocumentOutline,
  shieldOk: mdiShieldCheckOutline,
  shieldNo: mdiShieldOffOutline,
  trash: mdiDelete,
  iphone: mdiCellphone,
  route: mdiMapMarkerPath
}

export default {
  ...baseIcons,
  ...alternates
}
